routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Auth'], function (): void {
    Route::get('/', 'LoginController@showLoginForm');
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login.post');
    Route::get('/logout', 'LoginController@logout')->name('logout');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard/{id?}', 'DashboardController@index')->name('dashboard');
    Route::post('/dashboard/{id?}', 'DashboardController@index')->name('dashboard.post');
    Route::get('/analytics/{id?}', 'AnalyticsController@index')->name('analytics');
    Route::post('/analytics/{id?}', 'AnalyticsController@index')->name('analytics.post');
    Route::get('/applicants/{id?}', 'ApplicantController@index')->name('applicants');
    Route::post('/applicants/{id?}', 'ApplicantController@index')->name('applicants.post');
    Route::get('applicants/export/{id?}', 'ApplicantController@export')->name('applicants.export');

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/', 'PageController@index')->name('index');
        Route::get('/create', 'PageController@create')->name('create');
        Route::post('/save/{id?}', 'PageController@save')->name('save');
        Route::get('/edit/{id}', 'PageController@edit')->name('edit');
        Route::post('/delete', 'PageController@delete')->name('delete');
    });

    Route::group(['prefix' => 'forms', 'as' => 'forms.'], function () {
        Route::get('/', 'FormController@index')->name('index');
        Route::get('/create', 'FormController@create')->name('create');
        Route::post('/save/{id?}', 'FormController@save')->name('save');
        Route::get('/edit/{id}', 'FormController@edit')->name('edit');
        Route::post('/delete', 'FormController@delete')->name('delete');
    });

    Route::group(['prefix' => 'design', 'as' => 'design.'], function () {
        Route::get('/', 'MasterCssController@index')->name('index');
        Route::post('/', 'MasterCssController@save')->name('save');
    });

    Route::group(['prefix' => 'members', 'as' => 'members.'], function () {
        Route::get('/', 'MemberController@index')->name('index');
        Route::get('/create', 'MemberController@create')->name('create');
        Route::post('/save/{id?}', 'MemberController@save')->name('save');
        Route::get('/edit/{id}', 'MemberController@edit')->name('edit');
        Route::post('/delete', 'MemberController@delete')->name('delete');
        Route::get('/export', 'MemberController@export')->name('export');
    });

    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('/', 'ConfigController@index')->name('index');
        Route::post('/campaign', 'CampaignController@store')->name('campaign.store');
        Route::post('/fields', 'MasterFieldsController@save')->name('fields.save');
        Route::post('/user', 'UserFunctionalityController@save')->name('user.save');
        Route::post('/user/import', 'UserFunctionalityController@import')->name('user.import');
        Route::post('/security', 'SecurityController@save')->name('security.save');
    });
});

Route::get('/design/css', 'PromonFormController@showCSS')->name('dynamicForm.showCSS');
Route::get('/{permalink}', 'PromonFormController@show')->name('dynamicForm.show');
Route::post('/{permalink}', 'PromonFormController@save')->name('dynamicForm.save');

resources/views/analytics.blade.php
@extends('layouts.admin', [
    'title' => 'Promon | アナリティクス',
    'page_name' => 'analytics',
])

@section('content')
<div class="breadcrumbs__container clearfix">
    <div class="breadcrumbs">
        <ul>
            <li class="active"><a href="#">アナリティクス</a></li>
        </ul>
    </div>
</div> <!-- .breadcrumbs__container -->
<form method="post" action="#">
@csrf
    <div class="section">
        <div class="analyticsSelect">
            <select class="analyticsSelect" id="select_title" name="id" onChange="onChange_Form_TitleSelection(this)">
                <option value="" selected disabled>選択してください</option>
                @foreach($forms as $form)
                <option value="{{ $form->id }}" {{ Request::route('id') == $form->id ? 'selected' : '' }}>{{ $form->title }}</option>
                @endforeach
            </select>
        <div>
        <div class="section__row">
            <div class="chart">
                <canvas id="formChart"></canvas>
            </div>
        </div>
    </div>
    <div class="section form">
        <div class="section__row">
            <p class="section__label title">合計応募件数</p>
        </div>
        <div class="section__row">
            <div class="label">
               <h3><span>合計</span>{{ $analytics['allSubmittedForms'] }}<span>件</span></h3>
            </div>
            <div class="label label2" style="float: right">
                <h3>{{ $analytics['submittedForms'] }}<span>件</span></h3>
            </div>
        </div>
    </div><!-- .section -->
</form>
@endsection
@push('scripts')

<script>
    let chart_labels = {!! $analytics['labels'] !!};
    let chart_datasets = {!! json_encode($datasets) !!};

    function onChange_Form_TitleSelection(e){
        let form = $(e).closest('form');
        var url = "{{ route('analytics.post', ['id' => '_id' ]) }}".replace('_id', e.value);
        form.attr('action', url);
        form.submit();
    };

    $(function(){
	    chart();
    });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<script src="{{ asset('js/chart.js') }}"></script>
@endpush

resources/views/applicants.blade.php
@extends('layouts.admin', [
    'title' => 'Promon',
    'page_name' => 'applicant-list',
])

@section('content')
<div class="breadcrumbs__container clearfix">
    <div class="breadcrumbs">
        <ul>
            <li class="active"><a href="#">募集一覧</a></li>
        </ul>
    </div>
    <div class="breadcrumbs__btnContainer">
        <a href="{{ route('applicants.export', Request::route('id')) }}" class="bc__button">CSVダウンロード</a>
    </div>
</div> <!-- .breadcrumbs__container -->
<div class="section form addPad2">
    <div class="section__row">
        <form id="form_title" method="POST">
            <select id="select_title" name="id" onChange="onChange_Form_TitleSelection(this)">
                <option value="" selected disabled>選択してください</option>
                @foreach($forms as $form)
                <option value="{{ $form->id }}" {{ Request::route('id') == $form->id ? 'selected' : '' }}>{{ $form->title }}</option>
                @endforeach
            </select>
        </form>
    </div>
    <div class="section__row">
        <table id="dt-basic" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    @foreach($questions as $key => $question)
                    <td>{{ $question }}</td>
                    @endforeach
                </tr>
            </thead>
            <tbody>
            @foreach($answers as $answerkey => $answer)
            <tr>
                @foreach($questions as $questionKey => $question)
                <td>{{ isset($answer[$questionKey]) ? $answer[$questionKey] : '---' }}</td>   
                @endforeach
            </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection
@push('scripts')
<script>
    function onChange_Form_TitleSelection(e){
        let form = $(e).closest('form');
        var url = "{{ route('applicants.post', ['id' => '_id' ]) }}".replace('_id', e.value);
        form.attr('action', url);
        form.submit();
    };
    $(function(){
        $('#form_title').prepend('<input type="hidden" name="_token" value="{{ csrf_token() }}">');
        var form_title_id = $('#select_title').val()
        if(!form_title_id){
            $('.breadcrumbs__btnContainer').addClass('hide');
        }
    });
</script>
<script type="text/javascript" src="{{ asset('js/datatable.js') }}"></script>
@endpush

resources/views/dashboard.blade.php
@extends('layouts.admin', [
    'title' => 'Promon | ダッシュボード',
    'page_name' => 'dashboard',
])

@section('content')
<form method='post' action='#'>
@csrf
<div class="section">
    <div class="section__row">
        <p class="section__label">合計応募件数</p>
    </div>
    <div class="section__row">
        <div class="analyticsSelect dashboard">
            <select class="analyticsSelect" id="select_title" name="id" onChange="onChange_Form_TitleSelection(this)">
                <option value="" selected disabled>選択してください</option>
                @foreach($forms as $form)
                <option value="{{ $form->id }}" {{ Request::route('id') == $form->id ? 'selected' : '' }}>{{ $form->title }}</option>
                @endforeach
            </select>
        </div>
        <div class="incremental-counter" data-value="{{$analytics['submittedForms']}}">
        </div>
        <div class="chart">
            <canvas id="formChart"></canvas>
        </div>
    </div>
</div>
<div class="section">
    <div class="section__row">
        <p class="section__label">現在の表示 Promon</p>
    </div>
    <div class="section__row">
        <table id="dt-basic" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <td>キャンペーン名</td>
                    <td>公開期間</td>
                    <td>見せる</td>
                </tr>
            </thead>
            <tbody>
            @foreach($pages as $page)
            <tr>
                <td>{{ $campaign->name }}</td>
                <td>{{ $campaign->released_start_at->format('Y.m.d') }} ~ {{ $campaign->released_end_at->format('Y.m.d') }}</td>
                <td><a href="{{ route('dynamicForm.show', $page->permalink) }}" class="section__listItem--button" target="_blank">サイトをみる</a></td>
            </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection
@push('scripts')
<script>
    let chart_labels = {!! $analytics['labels'] !!};
    let chart_datasets = {!! json_encode($datasets) !!};
    let digitLength = {!! $analytics['submittedForms'] !!};

    function onChange_Form_TitleSelection(e){
        let form = $(e).closest('form');
        var url = "{{ route('dashboard.post', ['id' => '_id' ]) }}".replace('_id', e.value);
        form.attr('action', url);
        form.submit();
    };

    function numCounter(){
	$(".incremental-counter").incrementalCounter({
        "digits": digitLength.toString().length
        });
    }

    $(function(){
        chart();
        numCounter();
    });
</script>
<script src="{{ asset('js/counterjquery/jquery.incremental-counter.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<script src="{{ asset('js/chart.js') }}"></script>
@endpush

resources/views/design.blade.php
@extends('layouts.admin', [
    'title' => 'Promon | デサイン',
    'page_name' => 'design',
])

@section('content')
<div class="breadcrumbs__container clearfix">
    <div class="breadcrumbs">
        <ul>
            <li class="active"><a href="#">デサイン</a></li>
        </ul>
    </div>
</div> <!-- .breadcrumbs__container -->
<form method="post" action="{{ route('design.save') }}">
@csrf
    <div class="section form addPad">
        <div class="section__row">
            <textarea class="codemirror-textarea" name="content">{{ $masterCss->content }}</textarea>
        </div> <!-- .section__content -->
    </div><!-- .section -->
    <div class="btn__container">
        @if(Session::has('success_design'))
        <span class="success">{{ Session::get('success_design') }}</span>
        @endif
        <button type="submit" class="btn__container">更新</button>
    </div> <!-- .btn__container -->
</form>
@endsection
@push('scripts')
<script src="{{ asset('js/codemirror/codemirror.js') }}"></script>
<script src="{{ asset('js/codemirror/css.js') }}"></script>
<script src="{{ asset('js/codemirror.js') }}"></script>
<script>
@if ($errors->any())
  alert('{{ $errors->first('*') }}');
@endif
</script>
@endpush

resources/views/form.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{{ $page->meta_description }}">
    <meta name="keywords" content="{{ $page->meta_keyword }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ $page->meta_title ?? $page->title }}</title>

    <!-- OG Share Website -->
    <meta property="og:url" content="{{ $page->ogp_url }}" />
    <meta property="og:type" content="{{ $page->ogp_type ?? 'website' }}" />
    <meta property="og:title" content="{{ $page->ogp_title }}" />
    <meta property="og:description" content="{{ $page->ogp_description }}" />
    <meta property="og:image" content="{{ $page->ogp_image }}" />
    <meta property="og:image:secure_url" content="{{ $page->ogp_image }}" />

    <!-- Twitter Share -->
    <meta name="twitter:title" content="{{ $page->social_twitter_title }}">
    <meta name="twitter:image" content="{{ $page->social_twitter_image }}">
    <meta name="twitter:card" content="{{ $page->social_twitter_card ?? 'summary' }}">

    <link rel="stylesheet" media="print,screen" href="{{ route('dynamicForm.showCSS') }}">
</head>
<body>
    <!-- Use Facebook SDK -->
    <script>
        (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2&appId=2455177381176867&autoLogAppEvents=1';
        fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    {!! $page->content !!}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>
        $('form').on('submit', function(e){
            $(this).attr('action', '{{ $page->url }}');
        });
        $('form').prepend('<input type="hidden" name="_token" value="{{ csrf_token() }}">')
        @if ($errors->any())
            alert('{{ $errors->first('*') }}');
        @endif
    </script>
</body>
</html>