routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Auth'], function (): void {
    Route::get('/', 'LoginController@showLoginForm');
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login.post');
    Route::get('/logout', 'LoginController@logout')->name('logout');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard/{id?}', 'DashboardController@index')->name('dashboard');
    Route::post('/dashboard/{id?}', 'DashboardController@index')->name('dashboard.post');
    Route::get('/analytics/{id?}', 'AnalyticsController@index')->name('analytics');
    Route::post('/analytics/{id?}', 'AnalyticsController@index')->name('analytics.post');
    Route::get('/applicants/{id?}', 'ApplicantController@index')->name('applicants');
    Route::post('/applicants/{id?}', 'ApplicantController@index')->name('applicants.post');
    Route::get('applicants/export/{id?}', 'ApplicantController@export')->name('applicants.export');

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/', 'PageController@index')->name('index');
        Route::get('/create', 'PageController@create')->name('create');
        Route::post('/save/{id?}', 'PageController@save')->name('save');
        Route::get('/edit/{id}', 'PageController@edit')->name('edit');
        Route::post('/delete', 'PageController@delete')->name('delete');
    });

    Route::group(['prefix' => 'forms', 'as' => 'forms.'], function () {
        Route::get('/', 'FormController@index')->name('index');
        Route::get('/create', 'FormController@create')->name('create');
        Route::post('/save/{id?}', 'FormController@save')->name('save');
        Route::get('/edit/{id}', 'FormController@edit')->name('edit');
        Route::post('/delete', 'FormController@delete')->name('delete');
    });

    Route::group(['prefix' => 'design', 'as' => 'design.'], function () {
        Route::get('/', 'MasterCssController@index')->name('index');
        Route::post('/', 'MasterCssController@save')->name('save');
    });

    Route::group(['prefix' => 'members', 'as' => 'members.'], function () {
        Route::get('/', 'MemberController@index')->name('index');
        Route::get('/create', 'MemberController@create')->name('create');
        Route::post('/save/{id?}', 'MemberController@save')->name('save');
        Route::get('/edit/{id}', 'MemberController@edit')->name('edit');
        Route::post('/delete', 'MemberController@delete')->name('delete');
        Route::get('/export', 'MemberController@export')->name('export');
    });

    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('/', 'ConfigController@index')->name('index');
        Route::post('/campaign', 'CampaignController@store')->name('campaign.store');
        Route::post('/fields', 'MasterFieldsController@save')->name('fields.save');
        Route::post('/user', 'UserFunctionalityController@save')->name('user.save');
        Route::post('/user/import', 'UserFunctionalityController@import')->name('user.import');
        Route::post('/security', 'SecurityController@save')->name('security.save');
    });
});

Route::get('/design/css', 'PromonFormController@showCSS')->name('dynamicForm.showCSS');
Route::get('/{permalink}', 'PromonFormController@show')->name('dynamicForm.show');
Route::post('/{permalink}', 'PromonFormController@save')->name('dynamicForm.save');

app/Models/Member.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    public $timestamps = false;

    protected $hidden = ['id'];

    /**
     * Get table column names.
     *
     * @return collection
     */
    public function getTableColumns()
    {
        return $this->getConnection()->getSchemaBuilder()->getColumnListing($this->getTable());
    }
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use App\Exports\MembersExport;
use App\Models\Member;
use App\Models\MemberHeader;
use App\Services\MembersService;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Member       $member
     * @param MemberHeader $memberField
     * @return \Illuminate\Http\Response
     */
    public function index(Member $member, MemberHeader $memberField)
    {
        return view('members.index')
            ->with([
                'members' => $member,
                'memberField' => $memberField,
            ]);
    }

    /**
     * Go to create member form.
     *
     * @param Member         $member
     * @param MembersService $service
     * @return \Illuminate\Http\Response
     */
    public function create(MembersService $service)
    {
        $content = $service->generateContent();

        return view('members.create')
            ->with('content', $content);
    }

    /**
     * Save registered member in database.
     *
     * @param Member         $member
     * @param Request        $request
     * @param MembersService $service
     * @return \Illuminate\Http\Response
     */
    public function save(Request $request, MembersService $service)
    {
        if (!$request->route('id')) {
            $service->create($request->except('_token'));
        } else {
            $service->update(array_merge($request->except('_token'), ['id' => $request->route('id')]));
        }

        return redirect()->route('members.index');
    }

    /**
     * Get the details of specified member in database.
     *
     * @param $id
     * @param Member         $members
     * @param MembersService $service
     * @return \Illuminate\Http\Response
     */
    public function edit($id, MembersService $service)
    {
        $content = $service->generateContent($id);

        return view('members.create')
            ->with('content', $content);
    }

    /**
     * Bulk delete members.
     *
     * @param Request     $request
     * @param NewsService $service
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete(Request $request)
    {
        Member::whereIn('id', $request->id)->delete();

        return redirect()->route('members.index');
    }

    /**
     * Export the data from database.
     *
     * @return \Illuminate\Http\Response
     */
    public function export()
    {
        return Excel::download(new MembersExport, 'members' . date('Ymd_H.i.s') . '.csv');
    }
}

resources/views/members/create.blade.php
@extends('layouts.admin', [
'title' => 'Promon',
'page_name' => 'member-list',
])

@section('content')
<div class="breadcrumbs__container clearfix">
    <div class="breadcrumbs">
        <ul>
            <li>募集一覧</li>
            <li class="active"><a href="#">新規作成</a></li>
        </ul>
    </div>
</div> <!-- .breadcrumbs__container -->
<form method="POST" action="{{ route('members.save', Request::route('id') ?? null) }}" id="pageForm">
    @csrf
    <div class="section form">
        <div class="section__content no-top">
            <div class="section__content--table">
            {!! $content !!}
            </div> <!-- .section__content--table -->
        </div> <!-- .section__content -->
    </div><!-- .section -->
    <div class="btn__container">
        <button type="submit" class="btn__container">更新</button>
    </div> <!-- .btn__container -->
</form>
@endsection
@push('scripts')
<script>

function enableDisableButton(e){
    var textbox = document.getElementsByClassName(e);
    if(textbox[0].disabled){
        textbox[0].disabled = false;
    }else{
        textbox[0].disabled = true;
    }
}

@if ($errors->any())
  alert('{{ $errors->first('*') }}');
@endif
</script>
@endpush

resources/views/members/index.blade.php
@extends('layouts.admin', [
'title' => 'Promon',
'page_name' => 'member-list',
])

@section('content')
<div class="breadcrumbs__container clearfix">
    <div class="breadcrumbs">
        <ul>
            <li class="active"><a href="#">募集一覧</a></li>
        </ul>
    </div>
    <div class="breadcrumbs__btnContainer">
        <a href="{{ route('members.export') }}" class="bc__button">CSVダウンロード</a>
    </div>
    <div class="breadcrumbs__btnContainer">
            <a href="{{ route('members.create') }}" class="bc__button">+新規作成</a>
        </div>
</div> <!-- .breadcrumbs__container -->
<form method="post" action="{{ route('members.delete') }}">
@csrf
    <div class="section nosidepad">
        <div class="section__row">
            <div class="pages">
                <div class="thead all-pages">
                    <div class="tr">
                        <div class="td">
                            <div class="custom__checkbox">
                                <label>
                                    <input type="checkbox" name="page_all" id="selectAllBtn" value="1">
                                    <span class="btn"></span>
                                </label>
                            </div>
                            <p class="checkbox__label">一括削除</p>
                        </div>
                        <div class="td">
                            <p>&nbsp;</p>
                        </div>
                        <div class="td">
                            <p>&nbsp;</p>
                        </div>
                        <div class="td trash">
                            <button type="submit" id="btnSubmit" disabled><img src="{{ asset('images/icons/icon_trash.png') }}" alt=""></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section form addPad2">
        <div class="pages">
            <div class="section__row">
                <table id="dt-basic-checkbox" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th></th>
                            @foreach (array_except($members->getTableColumns(), 0) as $memberHeader)
                            <th class="th-sm">{{ $memberHeader }}</th>
                            @endforeach
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($members->all() as $member)
                    <tr>
                        <td>
                        <div class="custom__checkbox">
                                <label>
                                    <input type="checkbox" name="id[]" class="chkBoxId" value="{{ $member->id }}">
                                    <span class="btn"></span>
                                </label>
                            </div>
                        </td>
                        @foreach(array_except($member->find($member->id)->getAttributes(), 'id') as $key => $item)
                        <td>
                            <p class="data__label">
                            {{ preg_match('/^\$2y\$/', $item ) ? '<<!!Encrypted!!>>' : $item }}
                            </p>
                        </td>
                        @endforeach
                        <td><div class="pages__Btn"><a href="{{ route('members.edit', $member->id) }}"><p>編集</p></a></div></td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div> <!-- .section__content -->
        </div>
    </div><!-- .section -->
</form>
@endsection
@push('scripts')
<script>
    $('#selectAllBtn').click(function(event) {
        $(".chkBoxId").prop('checked', $(this).prop('checked'));
        chkboxCheck();
    });

    $('.chkBoxId').change(function () {
        chkboxCheck();
    });

    function chkboxCheck()
    {
        var chkBox = $('input.chkBoxId:checkbox:checked').length > 0;
        if(chkBox){
            $('#btnSubmit').attr('disabled', false);
        } else {
            $('#btnSubmit').attr('disabled', true);
        }
    }
</script>
<script type="text/javascript" src="{{ asset('js/datatable.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/mdbootstrap/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/mdbootstrap/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/mdbootstrap/mdb.min.js') }}"></script>
@endpush