routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Auth'], function (): void {
    Route::get('/', 'LoginController@showLoginForm');
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login.post');
    Route::get('/logout', 'LoginController@logout')->name('logout');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard/{id?}', 'DashboardController@index')->name('dashboard');
    Route::post('/dashboard/{id?}', 'DashboardController@index')->name('dashboard.post');
    Route::get('/analytics/{id?}', 'AnalyticsController@index')->name('analytics');
    Route::post('/analytics/{id?}', 'AnalyticsController@index')->name('analytics.post');
    Route::get('/applicants/{id?}', 'ApplicantController@index')->name('applicants');
    Route::post('/applicants/{id?}', 'ApplicantController@index')->name('applicants.post');
    Route::get('applicants/export/{id?}', 'ApplicantController@export')->name('applicants.export');

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/', 'PageController@index')->name('index');
        Route::get('/create', 'PageController@create')->name('create');
        Route::post('/save/{id?}', 'PageController@save')->name('save');
        Route::get('/edit/{id}', 'PageController@edit')->name('edit');
        Route::post('/delete', 'PageController@delete')->name('delete');
    });

    Route::group(['prefix' => 'forms', 'as' => 'forms.'], function () {
        Route::get('/', 'FormController@index')->name('index');
        Route::get('/create', 'FormController@create')->name('create');
        Route::post('/save/{id?}', 'FormController@save')->name('save');
        Route::get('/edit/{id}', 'FormController@edit')->name('edit');
        Route::post('/delete', 'FormController@delete')->name('delete');
    });

    Route::group(['prefix' => 'design', 'as' => 'design.'], function () {
        Route::get('/', 'MasterCssController@index')->name('index');
        Route::post('/', 'MasterCssController@save')->name('save');
    });

    Route::group(['prefix' => 'members', 'as' => 'members.'], function () {
        Route::get('/', 'MemberController@index')->name('index');
        Route::get('/create', 'MemberController@create')->name('create');
        Route::post('/save/{id?}', 'MemberController@save')->name('save');
        Route::get('/edit/{id}', 'MemberController@edit')->name('edit');
        Route::post('/delete', 'MemberController@delete')->name('delete');
        Route::get('/export', 'MemberController@export')->name('export');
    });

    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('/', 'ConfigController@index')->name('index');
        Route::post('/campaign', 'CampaignController@store')->name('campaign.store');
        Route::post('/fields', 'MasterFieldsController@save')->name('fields.save');
        Route::post('/user', 'UserFunctionalityController@save')->name('user.save');
        Route::post('/user/import', 'UserFunctionalityController@import')->name('user.import');
        Route::post('/security', 'SecurityController@save')->name('security.save');
    });
});

Route::get('/design/css', 'PromonFormController@showCSS')->name('dynamicForm.showCSS');
Route::get('/{permalink}', 'PromonFormController@show')->name('dynamicForm.show');
Route::post('/{permalink}', 'PromonFormController@save')->name('dynamicForm.save');

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\QuestionsRequest;
use App\Http\Resources\FormCollection;
use App\Models\Form;
use App\Models\MasterInput;
use App\Services\FormService;
use Illuminate\Http\Request;

class FormController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $forms = Form::all();

        return view('forms.index')
            ->with('forms', $forms);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $old = $request->session()->get('_old_input');
        $form = new FormCollection($old);
        $masterInputs = MasterInput::all();

        return view('forms.create')
            ->with('masterInputs', $masterInputs)
            ->with('form', $form);
    }

    /**
     * Save the new Form in database.
     *
     * @param FormService      $formService
     * @param QuestionsRequest $request
     * @return \Illuminate\Http\Response
     */
    public function save(FormService $formService, QuestionsRequest $request)
    {
        if (!$request->route('id')) {
            $formService->create($request->data());
        } else {
            $formService->update(array_merge(['id' => $request->route('id')], $request->data()));
        }

        return redirect()->route('forms.index');
    }

    /**
     * Get the details of specified form in database.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $form = Form::find($id);
        $form['questions'] = $form->questions->toArray();
        collect($form->config->toArray())->map(function ($value, $key) use ($form) {
            $form[$key] = $value;
        });
        $form['admin_emails'] = str_replace(['[', '"', ']'], '', explode(',', $form['admin_emails']));
        $form['user_emails'] = str_replace(['[', '"', ']'], '', explode(',', $form['user_emails']));
        $form = new FormCollection($form);

        $masterInputs = MasterInput::all();

        return view('forms.create')
            ->with('form', $form)
            ->with('masterInputs', $masterInputs);
    }

    /**
     * Bulk delete form.
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete(Request $request)
    {
        Form::whereIn('id', $request->id)->delete();

        return redirect()->route('forms.index');
    }
}

resources/views/forms/index.blade.php
@extends('layouts.admin', [
    'title' => 'Promon | フォーム 一覧',
    'page_name' => 'form_index',
])

@section('content')
<div class="breadcrumbs__container clearfix">
    <div class="breadcrumbs">
        <ul>
            <li class="active"><a href="#">フォーム</a></li>
        </ul>
    </div>
</div> <!-- .breadcrumbs__container -->
<form method="post" action="{{ route('forms.delete') }}">
@csrf
    <div class="section nosidepad">
        <div class="section__row">
            <div class="pages">
                <div class="thead all-pages">
                    <div class="tr">
                        <div class="td">
                            <div class="custom__checkbox">
                                <label>
                                    <input type="checkbox" name="page_all" id="selectAllBtn" value="1">
                                    <span class="btn"></span>
                                </label>
                            </div>
                            <div class="pages__Btn small"><button type="submit" id="btnSubmit" disabled><p>一括削除</p></button></div>
                        </div>
                        <div class="td"><p>&nbsp;</p></div>
                        <div class="td"><p>&nbsp;</p></div>
                        <div class="td"><div class="pages__Btn black"><a href="{{ route('forms.create') }}"><p>新規作成</p></a></div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section form addPad2">
        <div class="pages">
            <div class="section__row">
                <table id="dt-basic-checkbox" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <td></td>
                            <td>フォームタイトル</td>
                            <td>フォームID</td>
                            <td>作成日</td>
                            <td>&nbsp;</td>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($forms as $form)
                    <tr>
                        <td>
                            <div class="custom__checkbox">
                                <label>
                                    <input type="checkbox" name="id[]" class="chkBoxId" value="{{ $form->id }}">
                                    <span class="btn"></span>
                                </label>
                            </div>
                        </td>
                        <td><p class="data__label">{{ $form->title }}</p></td>
                        <td><p class="data__label">{{ $form->code }}</p></td>
                        <td><p class="data__label">{{ $form->updated_at->format('Y年m月d日') }}</p></td>
                        <td><div class="pages__Btn"><a href="{{ route('forms.edit', $form->id) }}"><p>編集</p></a></div></td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>
@endsection
@push('scripts')
<script>
    $('#selectAllBtn').click(function(event) {
        $(".chkBoxId").prop('checked', $(this).prop('checked'));
        chkboxCheck();
    });

    $('.chkBoxId').change(function () {
        chkboxCheck();
    });

    function chkboxCheck()
    {
        var chkBox = $('input.chkBoxId:checkbox:checked').length > 0;
        if(chkBox){
            $('#btnSubmit').attr('disabled', false);
        } else {
            $('#btnSubmit').attr('disabled', true);
        }
    }
</script>
<script type="text/javascript" src="{{ asset('js/datatable.js') }}"></script>
@endpush