routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Auth'], function (): void {
    Route::get('/', 'LoginController@showLoginForm');
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login.post');
    Route::get('/logout', 'LoginController@logout')->name('logout');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard/{id?}', 'DashboardController@index')->name('dashboard');
    Route::post('/dashboard/{id?}', 'DashboardController@index')->name('dashboard.post');
    Route::get('/analytics/{id?}', 'AnalyticsController@index')->name('analytics');
    Route::post('/analytics/{id?}', 'AnalyticsController@index')->name('analytics.post');
    Route::get('/applicants/{id?}', 'ApplicantController@index')->name('applicants');
    Route::post('/applicants/{id?}', 'ApplicantController@index')->name('applicants.post');
    Route::get('applicants/export/{id?}', 'ApplicantController@export')->name('applicants.export');

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/', 'PageController@index')->name('index');
        Route::get('/create', 'PageController@create')->name('create');
        Route::post('/save/{id?}', 'PageController@save')->name('save');
        Route::get('/edit/{id}', 'PageController@edit')->name('edit');
        Route::post('/delete', 'PageController@delete')->name('delete');
    });

    Route::group(['prefix' => 'forms', 'as' => 'forms.'], function () {
        Route::get('/', 'FormController@index')->name('index');
        Route::get('/create', 'FormController@create')->name('create');
        Route::post('/save/{id?}', 'FormController@save')->name('save');
        Route::get('/edit/{id}', 'FormController@edit')->name('edit');
        Route::post('/delete', 'FormController@delete')->name('delete');
    });

    Route::group(['prefix' => 'design', 'as' => 'design.'], function () {
        Route::get('/', 'MasterCssController@index')->name('index');
        Route::post('/', 'MasterCssController@save')->name('save');
    });

    Route::group(['prefix' => 'members', 'as' => 'members.'], function () {
        Route::get('/', 'MemberController@index')->name('index');
        Route::get('/create', 'MemberController@create')->name('create');
        Route::post('/save/{id?}', 'MemberController@save')->name('save');
        Route::get('/edit/{id}', 'MemberController@edit')->name('edit');
        Route::post('/delete', 'MemberController@delete')->name('delete');
        Route::get('/export', 'MemberController@export')->name('export');
    });

    Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
        Route::get('/', 'ConfigController@index')->name('index');
        Route::post('/campaign', 'CampaignController@store')->name('campaign.store');
        Route::post('/fields', 'MasterFieldsController@save')->name('fields.save');
        Route::post('/user', 'UserFunctionalityController@save')->name('user.save');
        Route::post('/user/import', 'UserFunctionalityController@import')->name('user.import');
        Route::post('/security', 'SecurityController@save')->name('security.save');
    });
});

Route::get('/design/css', 'PromonFormController@showCSS')->name('dynamicForm.showCSS');
Route::get('/{permalink}', 'PromonFormController@show')->name('dynamicForm.show');
Route::post('/{permalink}', 'PromonFormController@save')->name('dynamicForm.save');

resources/views/pages/create.blade.php
@extends('layouts.admin', [
    'title' => 'Promon | ページ作成',
    'page_name' => 'page_create',
])

@section('content')
<div class="breadcrumbs__container clearfix">
    <div class="breadcrumbs">
        <ul>
            <li>ページ</li>
            <li class="active"><a href="#">新規作成</a></li>
        </ul>
    </div>
</div> <!-- .breadcrumbs__container -->
<form method="POST" action="{{ route('pages.save', $page['id'] ?? null ) }}" id="pageForm">
    @csrf
    <div class="section">
        <div class="section__row">
            <p class="section__label">タイトル<i class="required">*</i></p>
            <div class="section__subContent">
                <input type="text" name="title" placeholder="PROMON" value="{{ $page['title'] ?? '' }}">
            </div>
            <div class="section__subContent">
                <div class="custom__checkbox">
                    <label>
                        <input type="checkbox" name="is_published" value="1" {{ isset($page['is_published']) && $page['is_published'] == '1' ? 'checked' : '' }}>
                        <span class="btn"></span>
                    </label>
                </div>
                <p class="section__checkbox--label">活性化した</p>
            </div>
        </div>
    </div>
    <div class="section nobg">
        <p class="section__label permalink">パーマリンク:<i class="required">*</i> {{ env('APP_URL') }}/ </p> <input type="text" name="permalink" value="{{ $page['permalink'] ?? '' }}">
    </div>
    <div class="section nobg">
        <textarea id="content-area" class="section__row site__preview" name="content">{{ html_entity_decode($page['content'] ?? '') }}</textarea>
    </div>
    <div class="section form">
        <div class="section__row">
            <p class="section__label title">OGP設定</p>
        </div>
        <div class="section__content">
            <div class="section__content--table">
                <div class="tr">
                    <div class="th">Title</div>
                    <div class="td">
                        <input type="text" name="ogp_title" value="{{ $page['ogp_title'] ?? '' }}">
                    </div>
                </div>
                <div class="tr">
                    <div class="th">Type</div>
                    <div class="td">
                        <input type="text" name="ogp_type" value="{{ $page['ogp_type'] ?? '' }}" placeholder="website">
                    </div>
                </div>
                <div class="tr">
                    <div class="th">URL</div>
                    <div class="td">
                        <input type="text" name="ogp_url" value="{{ $page['ogp_url'] ?? '' }}">
                    </div>
                </div>
                <div class="tr">
                    <div class="th">Img ull</div>
                    <div class="td">
                        <input type="text" name="ogp_image" value="{{ $page['ogp_image'] ?? '' }}">
                    </div>
                </div>
                <div class="tr">
                    <div class="th">Site name</div>
                    <div class="td">
                        <input type="text" name="ogp_site_name" value="{{ $page['ogp_site_name'] ?? '' }}">
                    </div>
                </div>
                <div class="tr">
                    <div class="th">Description</div>
                    <div class="td">
                        <input type="text" name="ogp_description" value="{{ $page['ogp_description'] ?? '' }}">
                    </div>
                </div>
            </div> <!-- .section__content--table -->
        </div> <!-- .section__content -->
    </div><!-- .section -->
    <div class="section form">
        <div class="section__row">
            <p class="section__label title">Facebook</p>
        </div>
        <div class="section__content">
            <div class="section__content--table">
                <div class="tr">
                    <div class="th">App ID</div>
                    <div class="td">
                        <input type="text" name="social_fb_app_id" value="{{ $page['social_fb_app_id'] ?? '' }}">
                    </div>
                </div>
                <div class="tr">
                    <div class="th">Admin ID</div>
                    <div class="td">
                        <input type="text" name="social_fb_admin_id" value="{{ $page['social_fb_admin_id'] ?? '' }}">
                    </div>
                </div>
            </div> <!-- .section__content--table -->
        </div> <!-- .section__content -->
    </div><!-- .section -->
    <div class="section form">
        <div class="section__row">
            <p class="section__label title">Twitter</p>
        </div>
        <div class="section__content">
            <div class="section__content--table">
                <div class="tr">
                    <div class="th">Title</div>
                    <div class="td">
                        <input type="text" name="social_twitter_title" value="{{ $page['social_twitter_title'] ?? '' }}">
                    </div>
                </div>
                <div class="tr">
                    <div class="th">Image</div>
                    <div class="td">
                        <input type="text" name="social_twitter_image" value="{{ $page['social_twitter_image'] ?? '' }}">
                    </div>
                </div>
                <div class="tr">
                    <div class="th">Card</div>
                    <div class="td">
                        <input type="text" name="social_twitter_card" value="{{ $page['social_twitter_card'] ?? '' }}" placeholder="summary">
                    </div>
                </div>
            </div> <!-- .section__content--table -->
        </div> <!-- .section__content -->
    </div><!-- .section -->
    <div class="section form">
        <div class="section__row">
            <p class="section__label title">Meta Tag</p>
        </div>
        <div class="section__content">
            <div class="section__content--table">
                <div class="tr">
                    <div class="th">Title</div>
                    <div class="td">
                        <input type="text" name="meta_title" value="{{ $page['meta_title'] ?? '' }}">
                    </div>
                </div>
                <div class="tr">
                    <div class="th">Description</div>
                    <div class="td">
                        <input type="text" name="meta_description" value="{{ $page['meta_description'] ?? '' }}">
                    </div>
                </div>
                <div class="tr">
                    <div class="th">Keyword</div>
                    <div class="td">
                        <input type="text" name="meta_keyword" value="{{ $page['meta_keyword'] ?? '' }}">
                    </div>
                </div>
            </div> <!-- .section__content--table -->
        </div> <!-- .section__content -->
    </div><!-- .section -->
    <div class="btn__container">
        <button type="submit" class="btn__container">更新</button>
    </div> <!-- .btn__container -->
</form>

@endsection
@push('scripts')
<script src="{{ asset('js/tinymce-plugins/tinymce.js') }}"></script>
<script src="{{ asset('js/tinymce.js') }}"></script>
<script>
@if ($errors->any())
  alert('{{ $errors->first('*') }}');
@endif
</script>
@endpush

resources/views/pages/index.blade.php
@extends('layouts.admin', [
    'title' => 'Promon | ページ 一覧',
    'page_name' => 'page_index',
])

@section('content')
<div class="breadcrumbs__container clearfix">
    <div class="breadcrumbs">
        <ul>
            <li class="active">ページ</li>
        </ul>
    </div>
    <div class="breadcrumbs__btnContainer">
        <a href="{{ route('pages.create') }}" class="bc__button"><span class="add"></span>新規作成</a>
    </div>
</div> <!-- .breadcrumbs__container -->
<form method="post" action="{{ route('pages.delete') }}">
@csrf
    <div class="section nosidepad">
        <div class="section__row">
            <div class="pages">
                <div class="thead all-pages">
                    <div class="tr">
                        <div class="td">
                            <div class="custom__checkbox">
                                <label>
                                    <input type="checkbox" name="page_all" id="selectAllBtn" value="1">
                                    <span class="btn"></span>
                                </label>
                            </div>
                            <p class="checkbox__label">一括削除</p>
                        </div>
                        <div class="td"><p>&nbsp;</p></div>
                        <div class="td"><p>&nbsp;</p></div>
                        <div class="td trash"><button type="submit" id="btnSubmit" disabled><img src="{{ asset('images/icons/icon_trash.png') }}" alt=""></button></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section form addPad2">
        <div class="pages">
            <div class="section__row">
                <table id="dt-basic-checkbox" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <td></td>
                            <td>ページタイトル</td>
                            <td>作成日</td>
                            <td>ステータス</td>
                            <td>&nbsp;</td>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($pages as $page)
                    <tr>
                        <td>
                            <div class="custom__checkbox">
                                <label>
                                    <input type="checkbox" name="id[]" class="chkBoxId" value="{{ $page->id }}">
                                    <span class="btn"></span>
                                </label>
                            </div>
                        </td>
                        <td>{{ $page->title }}</td>
                        <td>{{ $page->created_at->format('Y年m月d日') }}</td>
                        <td>{{ $page->is_published == '1' ? '公開中' : '非公開' }}</td>
                        <td><div class="pages__Btn"><a href="{{ route('pages.edit', $page->id) }}"><p>プレビュー</p></a></div></td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>
@endsection
@push('scripts')
<script>
    $('#selectAllBtn').click(function(event) {
        $(".chkBoxId").prop('checked', $(this).prop('checked'));
        chkboxCheck();
    });

    $('.chkBoxId').change(function () {
        chkboxCheck();
    });

    function chkboxCheck()
    {
        var chkBox = $('input.chkBoxId:checkbox:checked').length > 0;
        if(chkBox){
            $('#btnSubmit').attr('disabled', false);
        } else {
            $('#btnSubmit').attr('disabled', true);
        }
    }
</script>
<script type="text/javascript" src="{{ asset('js/datatable.js') }}"></script>
@endpush